# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1anegrfBEHVvbbJwHHNmom0Od1jfXx2lL
"""

import numpy as np
import pandas as pd

X=np.array([[-1,-1],[-1,1],[1,-1],[1,1]])
X

O=np.array([-1,-1,-1,1])
O=np.transpose(O)
O

# W=np.random.random([X.shape[1]])
# b=np.random.random(1)
W=np.array([1,0])
b=0
print(W,b)

sum=np.zeros(O.shape)
sum

def step(sum):
    if (sum>0.5):
        return 1
    elif(sum<-0.5):
        return -1
    else:
        return 0

n_epoch=5
learning_rate=1

for k in range (n_epoch):
    c=0
    for i in range(4):
        sum[i] = step(X[i][0]*W[0] + X[i][1]*W[1] +b)
        print(sum[i])
        print(X[i])
        print(O[i])
        if(sum[i]!=O[i]):
            print("HI")
            W[0]=W[0]+learning_rate*O[i]*X[i][0]
            W[1]=W[1]+learning_rate*O[i]*X[i][1]
            b=b+learning_rate*O[i]
        print(b)

W

b

